export * from "../common/const";
import * as C from "../common/const";

export const DefaultInfoURL="https://czandor.hu/fitbit/prog/info.php";
export const vibrateOptions=[
    {name:"None",             value:{id:"0"}},
    {name:"Bump",             value:{id:"1"}},
    {name:"Nudge",            value:{id:"2"}},
    {name:"Nudge Max",        value:{id:"3"}},
    {name:"Ping",             value:{id:"4"}},
    {name:"Confirmation",     value:{id:"5"}},
    {name:"Confirmation Max", value:{id:"6"}},
    {name:"Special",          value:{id:"7"}},
    {name:"Special Max",      value:{id:"8"}}
  ];
export const unitsSpeedOptions=[
    {name:"Default setting",   value:{id:""+C.UnitsDefault,info:'From Fitbit Setup',icon:'https://czandor.hu/fitbit/amongus/fitbit.png'}},
    {name:"Metric (kmh)",   value:{id:""+C.UnitsMetric,info:'Always Metric',icon:'https://czandor.hu/fitbit/amongus/metric.png'}},
    {name:"US (mph)",   value:{id:""+C.UnitsUS,info:'Always Imperial',icon:'https://czandor.hu/fitbit/amongus/imperial.png'}}
  ];

export const unitsDistanceOptions=[
    {name:"Default setting",   value:{id:""+C.UnitsDefault,info:'From Fitbit Setup',icon:'https://czandor.hu/fitbit/amongus/fitbit.png'}},
    {name:"Metric (meter, km)",   value:{id:""+C.UnitsMetric,info:'Always Metric',icon:'https://czandor.hu/fitbit/amongus/metric.png'}},
    {name:"US (miles)",   value:{id:""+C.UnitsUS,info:'Always Imperial',icon:'https://czandor.hu/fitbit/amongus/imperial.png'}}
  ];

export const unitsTempOptions=[
    {name:"Default setting",   value:{id:""+C.UnitsDefault,info:'From Fitbit Setup',icon:'https://czandor.hu/fitbit/amongus/fitbit.png'}},
    {name:"Metric (C°)",   value:{id:""+C.UnitsMetric,info:'Always Metric',icon:'https://czandor.hu/fitbit/amongus/metric.png'}},
    {name:"US (F°)",   value:{id:""+C.UnitsUS,info:'Always Imperial',icon:'https://czandor.hu/fitbit/amongus/imperial.png'}}
  ];

export const units24hOptions=[
    {name:"Default setting",   value:{id:""+C.UnitsDefault,info:'From Fitbit Setup',icon:'https://czandor.hu/fitbit/amongus/fitbit.png'}},
    {name:"24h",   value:{id:""+C.UnitsMetric,info:'Always 24-hour clock',icon:'https://czandor.hu/fitbit/amongus/h24.png'}},
    {name:"12h",   value:{id:""+C.UnitsUS,info:'Always 12-hour clock',icon:'https://czandor.hu/fitbit/amongus/h12.png'}}
  ];

export const barOptions=[
    {name:"Default setting",   value:{id:""+C.SETTINGS_SYSTEMDEFAULT,info:'From Fitbit Setup',icon:'https://czandor.hu/fitbit/amongus/fitbit.png'}},
    {name:"Battery",   value:{id:""+C.HEALTH_battery,info:'Battery',icon:'https://czandor.hu/fitbit/amongus/empty.png'}},
    {name:"Steps",   value:{id:""+C.HEALTH_steps,info:'Number of steps taken',icon:'https://czandor.hu/fitbit/amongus/steps.png'}},
    {name:"Distance",   value:{id:""+C.HEALTH_distance,info:'Distance traveled',icon:'https://czandor.hu/fitbit/amongus/distance.png'}},
    {name:"Calories",   value:{id:""+C.HEALTH_calories,info:'Number of calories burned',icon:'https://czandor.hu/fitbit/amongus/calories.png'}},
    {name:"Elevation Gain",   value:{id:""+C.HEALTH_elevationGain,info:'Elevation gain',icon:'https://czandor.hu/fitbit/amongus/elevationGain.png'}},
    {name:"Active Zone Minutes",   value:{id:""+C.HEALTH_activeZoneMinutes,info:'The Zone Minutes spent in each of the heart rate zones that relate to physical activity',icon:'https://czandor.hu/fitbit/amongus/activeZoneMinutes.png'}}
]
export const weatherPeriodOptions=[
    {name:"6 hours",   value:{id:"360"}},
    {name:"3 hours",   value:{id:"180"}},
    {name:"2 hours",   value:{id:"120"}},
    {name:"90 minutes",   value:{id:"90"}},
    {name:"60 minutes",   value:{id:"60"}},
    {name:"50 minutes",   value:{id:"50"}},
    {name:"40 minutes",   value:{id:"40"}},
    {name:"30 minutes",   value:{id:"30"}},
    {name:"20 minutes",   value:{id:"20"}}/*,
    {name:"10 minutes",   value:"10"}/*,
    {name:"Below 10%",   value:"10"},
    {name:"Never",   value:"0"}*/
  ];
export const infoPeriodOptions=[
    {name:"6 hours",   value:{id:"360"}},
    {name:"3 hours",   value:{id:"180"}},
    {name:"2 hours",   value:{id:"120"}},
    {name:"90 minutes",   value:{id:"90"}},
    {name:"60 minutes",   value:{id:"60"}},
    {name:"50 minutes",   value:{id:"50"}},
    {name:"40 minutes",   value:{id:"40"}},
    {name:"30 minutes",   value:{id:"30"}},
    {name:"20 minutes",   value:{id:"20"}},
    {name:"15 minutes",   value:{id:"15"}}/*,
    {name:"Below 10%",   value:"10"},
    {name:"Never",   value:"0"}*/
  ];

export const aryIannaTimeZones = [
    'Europe/Andorra',
    'Asia/Dubai',
    'Asia/Kabul',
    'Europe/Tirane',
    'Asia/Yerevan',
    'Antarctica/Casey',
    'Antarctica/Davis',
    'Antarctica/DumontDUrville', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
    'Antarctica/Mawson',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Antarctica/Syowa',
    'Antarctica/Troll',
    'Antarctica/Vostok',
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Cordoba',
    'America/Argentina/Salta',
    'America/Argentina/Jujuy',
    'America/Argentina/Tucuman',
    'America/Argentina/Catamarca',
    'America/Argentina/La_Rioja',
    'America/Argentina/San_Juan',
    'America/Argentina/Mendoza',
    'America/Argentina/San_Luis',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Ushuaia',
    'Pacific/Pago_Pago',
    'Europe/Vienna',
    'Australia/Lord_Howe',
    'Antarctica/Macquarie',
    'Australia/Hobart',
    'Australia/Currie',
    'Australia/Melbourne',
    'Australia/Sydney',
    'Australia/Broken_Hill',
    'Australia/Brisbane',
    'Australia/Lindeman',
    'Australia/Adelaide',
    'Australia/Darwin',
    'Australia/Perth',
    'Australia/Eucla',
    'Asia/Baku',
    'America/Barbados',
    'Asia/Dhaka',
    'Europe/Brussels',
    'Europe/Sofia',
    'Atlantic/Bermuda',
    'Asia/Brunei',
    'America/La_Paz',
    'America/Noronha',
    'America/Belem',
    'America/Fortaleza',
    'America/Recife',
    'America/Araguaina',
    'America/Maceio',
    'America/Bahia',
    'America/Sao_Paulo',
    'America/Campo_Grande',
    'America/Cuiaba',
    'America/Santarem',
    'America/Porto_Velho',
    'America/Boa_Vista',
    'America/Manaus',
    'America/Eirunepe',
    'America/Rio_Branco',
    'America/Nassau',
    'Asia/Thimphu',
    'Europe/Minsk',
    'America/Belize',
    'America/St_Johns',
    'America/Halifax',
    'America/Glace_Bay',
    'America/Moncton',
    'America/Goose_Bay',
    'America/Blanc-Sablon',
    'America/Toronto',
    'America/Nipigon',
    'America/Thunder_Bay',
    'America/Iqaluit',
    'America/Pangnirtung',
    'America/Atikokan',
    'America/Winnipeg',
    'America/Rainy_River',
    'America/Resolute',
    'America/Rankin_Inlet',
    'America/Regina',
    'America/Swift_Current',
    'America/Edmonton',
    'America/Cambridge_Bay',
    'America/Yellowknife',
    'America/Inuvik',
    'America/Creston',
    'America/Dawson_Creek',
    'America/Fort_Nelson',
    'America/Vancouver',
    'America/Whitehorse',
    'America/Dawson',
    'Indian/Cocos',
    'Europe/Zurich',
    'Africa/Abidjan',
    'Pacific/Rarotonga',
    'America/Santiago',
    'America/Punta_Arenas',
    'Pacific/Easter',
    'Asia/Shanghai',
    'Asia/Urumqi',
    'America/Bogota',
    'America/Costa_Rica',
    'America/Havana',
    'Atlantic/Cape_Verde',
    'America/Curacao',
    'Indian/Christmas',
    'Asia/Nicosia',
    'Asia/Famagusta',
    'Europe/Prague',
    'Europe/Berlin',
    'Europe/Copenhagen',
    'America/Santo_Domingo',
    'Africa/Algiers',
    'America/Guayaquil',
    'Pacific/Galapagos',
    'Europe/Tallinn',
    'Africa/Cairo',
    'Africa/El_Aaiun',
    'Europe/Madrid',
    'Africa/Ceuta',
    'Atlantic/Canary',
    'Europe/Helsinki',
    'Pacific/Fiji',
    'Atlantic/Stanley',
    'Pacific/Chuuk',
    'Pacific/Pohnpei',
    'Pacific/Kosrae',
    'Atlantic/Faroe',
    'Europe/Paris',
    'Europe/London',
    'Asia/Tbilisi',
    'America/Cayenne',
    'Africa/Accra',
    'Europe/Gibraltar',
    'America/Godthab',
    'America/Danmarkshavn',
    'America/Scoresbysund',
    'America/Thule',
    'Europe/Athens',
    'Atlantic/South_Georgia',
    'America/Guatemala',
    'Pacific/Guam',
    'Africa/Bissau',
    'America/Guyana',
    'Asia/Hong_Kong',
    'America/Tegucigalpa',
    'America/Port-au-Prince',
    'Europe/Budapest',
    'Asia/Jakarta',
    'Asia/Pontianak',
    'Asia/Makassar',
    'Asia/Jayapura',
    'Europe/Dublin',
    'Asia/Jerusalem',
    'Asia/Kolkata',
    'Indian/Chagos',
    'Asia/Baghdad',
    'Asia/Tehran',
    'Atlantic/Reykjavik',
    'Europe/Rome',
    'America/Jamaica',
    'Asia/Amman',
    'Asia/Tokyo',
    'Africa/Nairobi',
    'Asia/Bishkek',
    'Pacific/Tarawa',
    'Pacific/Enderbury',
    'Pacific/Kiritimati',
    'Asia/Pyongyang',
    'Asia/Seoul',
    'Asia/Almaty',
    'Asia/Qyzylorda',
    'Asia/Qostanay', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
    'Asia/Aqtobe',
    'Asia/Aqtau',
    'Asia/Atyrau',
    'Asia/Oral',
    'Asia/Beirut',
    'Asia/Colombo',
    'Africa/Monrovia',
    'Europe/Vilnius',
    'Europe/Luxembourg',
    'Europe/Riga',
    'Africa/Tripoli',
    'Africa/Casablanca',
    'Europe/Monaco',
    'Europe/Chisinau',
    'Pacific/Majuro',
    'Pacific/Kwajalein',
    'Asia/Yangon',
    'Asia/Ulaanbaatar',
    'Asia/Hovd',
    'Asia/Choibalsan',
    'Asia/Macau',
    'America/Martinique',
    'Europe/Malta',
    'Indian/Mauritius',
    'Indian/Maldives',
    'America/Mexico_City',
    'America/Cancun',
    'America/Merida',
    'America/Monterrey',
    'America/Matamoros',
    'America/Mazatlan',
    'America/Chihuahua',
    'America/Ojinaga',
    'America/Hermosillo',
    'America/Tijuana',
    'America/Bahia_Banderas',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Africa/Maputo',
    'Africa/Windhoek',
    'Pacific/Noumea',
    'Pacific/Norfolk',
    'Africa/Lagos',
    'America/Managua',
    'Europe/Amsterdam',
    'Europe/Oslo',
    'Asia/Kathmandu',
    'Pacific/Nauru',
    'Pacific/Niue',
    'Pacific/Auckland',
    'Pacific/Chatham',
    'America/Panama',
    'America/Lima',
    'Pacific/Tahiti',
    'Pacific/Marquesas',
    'Pacific/Gambier',
    'Pacific/Port_Moresby',
    'Pacific/Bougainville',
    'Asia/Manila',
    'Asia/Karachi',
    'Europe/Warsaw',
    'America/Miquelon',
    'Pacific/Pitcairn',
    'America/Puerto_Rico',
    'Asia/Gaza',
    'Asia/Hebron',
    'Europe/Lisbon',
    'Atlantic/Madeira',
    'Atlantic/Azores',
    'Pacific/Palau',
    'America/Asuncion',
    'Asia/Qatar',
    'Indian/Reunion',
    'Europe/Bucharest',
    'Europe/Belgrade',
    'Europe/Kaliningrad',
    'Europe/Moscow',
    'Europe/Simferopol',
    'Europe/Kirov',
    'Europe/Astrakhan',
    'Europe/Volgograd',
    'Europe/Saratov',
    'Europe/Ulyanovsk',
    'Europe/Samara',
    'Asia/Yekaterinburg',
    'Asia/Omsk',
    'Asia/Novosibirsk',
    'Asia/Barnaul',
    'Asia/Tomsk',
    'Asia/Novokuznetsk',
    'Asia/Krasnoyarsk',
    'Asia/Irkutsk',
    'Asia/Chita',
    'Asia/Yakutsk',
    'Asia/Khandyga',
    'Asia/Vladivostok',
    'Asia/Ust-Nera',
    'Asia/Magadan',
    'Asia/Sakhalin',
    'Asia/Srednekolymsk',
    'Asia/Kamchatka',
    'Asia/Anadyr',
    'Asia/Riyadh',
    'Pacific/Guadalcanal',
    'Indian/Mahe',
    'Africa/Khartoum',
    'Europe/Stockholm',
    'Asia/Singapore',
    'America/Paramaribo',
    'Africa/Juba',
    'Africa/Sao_Tome',
    'America/El_Salvador',
    'Asia/Damascus',
    'America/Grand_Turk',
    'Africa/Ndjamena',
    'Indian/Kerguelen',
    'Asia/Bangkok',
    'Asia/Dushanbe',
    'Pacific/Fakaofo',
    'Asia/Dili',
    'Asia/Ashgabat',
    'Africa/Tunis',
    'Pacific/Tongatapu',
    'Europe/Istanbul',
    'America/Port_of_Spain',
    'Pacific/Funafuti',
    'Asia/Taipei',
    'Europe/Kiev',
    'Europe/Uzhgorod',
    'Europe/Zaporozhye',
    'Pacific/Wake',
    'America/New_York',
    'America/Detroit',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Indiana/Indianapolis',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Vevay',
    'America/Chicago',
    'America/Indiana/Tell_City',
    'America/Indiana/Knox',
    'America/Menominee',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/North_Dakota/Beulah',
    'America/Denver',
    'America/Boise',
    'America/Phoenix',
    'America/Los_Angeles',
    'America/Anchorage',
    'America/Juneau',
    'America/Sitka',
    'America/Metlakatla',
    'America/Yakutat',
    'America/Nome',
    'America/Adak',
    'Pacific/Honolulu',
    'America/Montevideo',
    'Asia/Samarkand',
    'Asia/Tashkent',
    'America/Caracas',
    'Asia/Ho_Chi_Minh',
    'Pacific/Efate',
    'Pacific/Wallis',
    'Pacific/Apia',
    'Africa/Johannesburg'
  ];
/*
export const msTimeZones=[
  [0, "Dateline Standard Time", "(GMT-12:00) International Date Line West"],
  [1, "Samoa Standard Time", "(GMT-11:00) Midway Island, Samoa"],
  [2, "Hawaiian Standard Time", "(GMT-10:00) Hawaii"],
  [3, "Alaskan Standard Time", "(GMT-09:00) Alaska"],
  [4, "Pacific Standard Time", "(GMT-08:00) Pacific Time (US and Canada); Tijuana"],
  [10, "Mountain Standard Time", "(GMT-07:00) Mountain Time (US and Canada)"],
  [13, "Mexico Standard Time 2", "(GMT-07:00) Chihuahua, La Paz, Mazatlan"],
  [15, "U.S. Mountain Standard Time", "(GMT-07:00) Arizona"],
  [20, "Central Standard Time", "(GMT-06:00) Central Time (US and Canada"],
  [25, "Canada Central Standard Time", "(GMT-06:00) Saskatchewan"],
  [30, "Mexico Standard Time", "(GMT-06:00) Guadalajara, Mexico City, Monterrey"],
  [33, "Central America Standard Time", "(GMT-06:00) Central America"],
  [35, "Eastern Standard Time", "(GMT-05:00) Eastern Time (US and Canada)"],
  [40, "U.S. Eastern Standard Time", "(GMT-05:00) Indiana (East)"],
  [45, "S.A. Pacific Standard Time", "(GMT-05:00) Bogota, Lima, Quito"],
  [50, "Atlantic Standard Time", "(GMT-04:00) Atlantic Time (Canada)"],
  [55, "S.A. Western Standard Time", "(GMT-04:00) Caracas, La Paz"],
  [56, "Pacific S.A. Standard Time", "(GMT-04:00) Santiago"],
  [60, "Newfoundland and Labrador Standard Time", "(GMT-03:30) Newfoundland and Labrador"],
  [65, "E. South America Standard Time", "(GMT-03:00) Brasilia"],
  [70, "S.A. Eastern Standard Time", "(GMT-03:00) Buenos Aires, Georgetown"],
  [73, "Greenland Standard Time", "(GMT-03:00) Greenland"],
  [75, "Mid-Atlantic Standard Time", "(GMT-02:00) Mid-Atlantic"],
  [80, "Azores Standard Time", "(GMT-01:00) Azores"],
  [83, "Cape Verde Standard Time", "(GMT-01:00) Cape Verde Islands"],
  [85, "GMT Standard Time", "(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London"],
  [90, "Greenwich Standard Time", "(GMT) Casablanca, Monrovia"],
  [95, "Central Europe Standard Time", "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague"],
  [100, "Central European Standard Time", "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb"],
  [105, "Romance Standard Time", "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris"],
  [110, "W. Europe Standard Time", "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna"],
  [113, "W. Central Africa Standard Time", "(GMT+01:00) West Central Africa"],
  [115, "E. Europe Standard Time", "(GMT+02:00) Bucharest"],
  [120, "Egypt Standard Time", "(GMT+02:00) Cairo"],
  [125, "FLE Standard Time", "(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius"],
  [130, "GTB Standard Time", "(GMT+02:00) Athens, Istanbul, Minsk"],
  [135, "Israel Standard Time", "(GMT+02:00) Jerusalem"],
  [140, "South Africa Standard Time", "(GMT+02:00) Harare, Pretoria"],
  [145, "Russian Standard Time", "(GMT+03:00) Moscow, St. Petersburg, Volgograd"],
  [150, "Arab Standard Time", "(GMT+03:00) Kuwait, Riyadh"],
  [155, "E. Africa Standard Time", "(GMT+03:00) Nairobi"],
  [158, "Arabic Standard Time", "(GMT+03:00) Baghdad"],
  [160, "Iran Standard Time", "(GMT+03:30) Tehran"],
  [165, "Arabian Standard Time", "(GMT+04:00) Abu Dhabi, Muscat"],
  [170, "Caucasus Standard Time", "(GMT+04:00) Baku, Tbilisi, Yerevan"],
  [175, "Transitional Islamic State of Afghanistan Standard Time", "(GMT+04:30) Kabul"],
  [180, "Ekaterinburg Standard Time", "(GMT+05:00) Ekaterinburg"],
  [185, "West Asia Standard Time", "(GMT+05:00) Islamabad, Karachi, Tashkent"],
  [190, "India Standard Time", "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi"],
  [193, "Nepal Standard Time", "(GMT+05:45) Kathmandu"],
  [195, "Central Asia Standard Time", "(GMT+06:00) Astana, Dhaka"],
  [200, "Sri Lanka Standard Time", "(GMT+06:00) Sri Jayawardenepura"],
  [201, "N. Central Asia Standard Time", "(GMT+06:00) Almaty, Novosibirsk"],
  [203, "Myanmar Standard Time", "(GMT+06:30) Yangon Rangoon"],
  [205, "S.E. Asia Standard Time", "(GMT+07:00) Bangkok, Hanoi, Jakarta"],
  [207, "North Asia Standard Time", "(GMT+07:00) Krasnoyarsk"],
  [210, "China Standard Time", "(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi"],
  [215, "Singapore Standard Time", "(GMT+08:00) Kuala Lumpur, Singapore"],
  [220, "Taipei Standard Time", "(GMT+08:00) Taipei"],
  [225, "W. Australia Standard Time", "(GMT+08:00) Perth"],
  [227, "North Asia East Standard Time", "(GMT+08:00) Irkutsk, Ulaanbaatar"],
  [230, "Korea Standard Time", "(GMT+09:00) Seoul"],
  [235, "Tokyo Standard Time", "(GMT+09:00) Osaka, Sapporo, Tokyo"],
  [240, "Yakutsk Standard Time", "(GMT+09:00) Yakutsk"],
  [245, "A.U.S. Central Standard Time", "(GMT+09:30) Darwin"],
  [250, "Cen. Australia Standard Time", "(GMT+09:30) Adelaide"],
  [255, "A.U.S. Eastern Standard Time", "(GMT+10:00) Canberra, Melbourne, Sydney"],
  [260, "E. Australia Standard Time", "(GMT+10:00) Brisbane"],
  [265, "Tasmania Standard Time", "(GMT+10:00) Hobart"],
  [270, "Vladivostok Standard Time", "(GMT+10:00) Vladivostok"],
  [275, "West Pacific Standard Time", "(GMT+10:00) Guam, Port Moresby"],
  [280, "Central Pacific Standard Time", "(GMT+11:00) Magadan, Solomon Islands, New Caledonia"],
  [285, "Fiji Islands Standard Time", "(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands"],
  [290, "New Zealand Standard Time", "(GMT+12:00) Auckland, Wellington"],
  [300, "Tonga Standard Time", "(GMT+13:00) Nuku'alofa"]
];
*/
export const minimalTimezoneSet = [
  { offset: '-11:00', label: '(GMT-11:00) Pago Pago', tzCode: 'Pacific/Pago_Pago' },
  { offset: '-10:00', label: '(GMT-10:00) Hawaii Time', tzCode: 'Pacific/Honolulu' },
  { offset: '-10:00', label: '(GMT-10:00) Tahiti', tzCode: 'Pacific/Tahiti' },
  { offset: '-09:00', label: '(GMT-09:00) Alaska Time', tzCode: 'America/Anchorage' },
  { offset: '-08:00', label: '(GMT-08:00) Pacific Time', tzCode: 'America/Los_Angeles' },
  { offset: '-07:00', label: '(GMT-07:00) Mountain Time', tzCode: 'America/Denver' },
  { offset: '-06:00', label: '(GMT-06:00) Central Time', tzCode: 'America/Chicago' },
  { offset: '-05:00', label: '(GMT-05:00) Eastern Time', tzCode: 'America/New_York' },
  { offset: '-04:00', label: '(GMT-04:00) Atlantic Time - Halifax', tzCode: 'America/Halifax' },
  { offset: '-03:00', label: '(GMT-03:00) Buenos Aires', tzCode: 'America/Argentina/Buenos_Aires' },
  { offset: '-02:00', label: '(GMT-02:00) Sao Paulo', tzCode: 'America/Sao_Paulo' },
  { offset: '-01:00', label: '(GMT-01:00) Azores', tzCode: 'Atlantic/Azores' },
  { offset: '+00:00', label: '(GMT+00:00) London', tzCode: 'Europe/London' },
  { offset: '+01:00', label: '(GMT+01:00) Berlin', tzCode: 'Europe/Berlin' },
  { offset: '+02:00', label: '(GMT+02:00) Helsinki', tzCode: 'Europe/Helsinki' },
  { offset: '+03:00', label: '(GMT+03:00) Istanbul', tzCode: 'Europe/Istanbul' },
  { offset: '+04:00', label: '(GMT+04:00) Dubai', tzCode: 'Asia/Dubai' },
  { offset: '+04:30', label: '(GMT+04:30) Kabul', tzCode: 'Asia/Kabul' },
  { offset: '+05:00', label: '(GMT+05:00) Maldives', tzCode: 'Indian/Maldives' },
  { offset: '+05:30', label: '(GMT+05:30) India Standard Time', tzCode: 'Asia/Kolkata' },
  { offset: '+05:45', label: '(GMT+05:45) Kathmandu', tzCode: 'Asia/Kathmandu' },
  { offset: '+06:00', label: '(GMT+06:00) Dhaka', tzCode: 'Asia/Dhaka' },
  { offset: '+06:30', label: '(GMT+06:30) Cocos', tzCode: 'Indian/Cocos' },
  { offset: '+07:00', label: '(GMT+07:00) Bangkok', tzCode: 'Asia/Bangkok' },
  { offset: '+08:00', label: '(GMT+08:00) Hong Kong', tzCode: 'Asia/Hong_Kong' },
  { offset: '+08:30', label: '(GMT+08:30) Pyongyang', tzCode: 'Asia/Pyongyang' },
  { offset: '+09:00', label: '(GMT+09:00) Tokyo', tzCode: 'Asia/Tokyo' },
  { offset: '+09:30', label: '(GMT+09:30) Central Time - Darwin', tzCode: 'Australia/Darwin' },
  { offset: '+10:00', label: '(GMT+10:00) Eastern Time - Brisbane', tzCode: 'Australia/Brisbane' },
  { offset: '+10:30', label: '(GMT+10:30) Central Time - Adelaide', tzCode: 'Australia/Adelaide' },
  { offset: '+11:00', label: '(GMT+11:00) Eastern Time - Melbourne, Sydney', tzCode: 'Australia/Sydney' },
  { offset: '+12:00', label: '(GMT+12:00) Nauru', tzCode: 'Pacific/Nauru' },
  { offset: '+13:00', label: '(GMT+13:00) Auckland', tzCode: 'Pacific/Auckland' },
  { offset: '+14:00', label: '(GMT+14:00) Kiritimati', tzCode: 'Pacific/Kiritimati' }
];
